# =========================================================================
# MIGRATION NOTICE: CloudFormation → CDK
# =========================================================================
# This CloudFormation template has been REPLACED with AWS CDK infrastructure
# 
# NEW DEPLOYMENT LOCATION: ./cdk/ directory
# 
# To deploy this service:
# 1. cd cdk/
# 2. npm install
# 3. npm run deploy:code   (for CODE environment)
# 4. npm run deploy:prod   (for PROD environment)
# 
# CDK Benefits:
# - Type-safe infrastructure as code
# - Better integration with Guardian CDK patterns
# - Improved testing and validation
# - Consistent deployment patterns across Guardian services
# 
# This file is kept for historical reference only.
# =========================================================================

AWSTemplateFormatVersion: '2010-09-09'
Description: 'DEPRECATED - This infrastructure has been migrated to CDK. See cdk/ directory.'

Parameters:
  Notice:
    Type: String
    Default: 'This template is deprecated. Use CDK in the cdk/ directory.'
    Description: 'Migration notice for operators'

Resources:
  # This is a placeholder resource to make the template valid
  # The actual infrastructure is now defined in CDK
  MigrationNotice:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  MigrationNotice:
    Description: 'This infrastructure has been migrated to CDK. Use the cdk/ directory for deployment.'
    Value: 'Use: cd cdk && npm run deploy'
  
  CDKCommands:
    Description: 'Commands to deploy via CDK'
    Value: 'CODE: npm run deploy:code | PROD: npm run deploy:prod'
