name: Build image-url-signing-service

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  image-url-signing-service-build:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.event.pull_request.head.repo.owner.login == 'guardian' ||
          github.event_name == 'push')

    name: image-url-signing-service build
    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Test + build
        run: |
          npm install -g yarn
          yarn install
          yarn lint
          yarn test
          yarn build

          cp package.json dist/
          cp yarn.lock dist/
          cd dist
          yarn install --production
          zip -r image-url-signing-service ./*
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Riff-Raff
        uses: guardian/actions-riff-raff@v2
        with:
          projectName: targeting:image-url-signing-service
          buildNumberOffset: 1000
          config: |
            stacks:
              - targeting
            regions:
              - eu-west-1
            allowedStages:
              - CODE
              - PROD
            deployments:
              cloudformation:
                type: cloud-formation
                app: image-url-signing-service
                parameters:
                  cloudFormationStackName: image-url-signing-service 
                  prependStackToCloudFormationStackName: true
                  templateStagePaths:
                    CODE: cfn.yaml
                    PROD: cfn.yaml

              image-url-signing-service:
                type: aws-lambda
                dependencies: [ cloudformation ]
                parameters:
                  prefixStack: false
                  fileName: image-url-signing-service.zip
                  functionNames:
                    - image-url-signing-service-

          contentDirectories: |
            image-url-signing-service:
              - dist/image-url-signing-service.zip
            cloudformation:
              - cfn.yaml
