name: Build image-url-signing-service

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  image-url-signing-service-build:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.event.pull_request.head.repo.owner.login == 'guardian' ||
          github.event_name == 'push')

    name: image-url-signing-service build
    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Test + build
        run: |
          npm install -g yarn
          yarn install
          yarn test
          yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Riff-Raff
        run: |
          export LAST_TEAMCITY_BUILD=1000
          export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
          yarn riffraff
