name: jest
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: guardian/actions-setup-node@main

      # Cache npm dependencies using https://github.com/bahmutov/npm-install
      - uses: bahmutov/npm-install@v1

      - run: CI=true yarn test
